name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      – '*'
      
jobs:
  tests:
    runs-on: macos-latest
    steps:
    – name: Run macOS tests
      run: swift test -v
    – name: Run iOS tests
      run: sh ./Scripts/ci-ios-code-coverage.sh
