name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      – '*'

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - name: Swift Coverage Report
      uses: maxep/spm-lcov-action@0.3.1

