name: Deploy DocC to Github Pages
on:
  # Manual run
  workflow_dispatch:
  # Runs on pushes targeting the master branch
  # push:
  #   branches: ["master"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # One deployment deploy job since we're just deploying
  deploy:
    environment:
      # Must set to this for deploying to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Force Xcode 13.3.1
        run: sudo xcode-select -s "/Applications/Xcode_13.3.1.app"

      - name: Build DocC
        run: |
          # Variables configurables
          SCHEME_NAME="AnnotationSwift"
          OUTPUT_DIR="./docs"
          PROJECT_NAME="AnnotationSwift"

          # Limpiar el directorio de compilación y la caché de módulos
          rm -rf .build
          rm -rf ~/Library/Developer/Xcode/DerivedData

          # Generar la documentación
          swift package --allow-writing-to-directory ${OUTPUT_DIR} \
              generate-documentation --target ${SCHEME_NAME} \
              --disable-indexing \
              --transform-for-static-hosting \
              --hosting-base-path ${PROJECT_NAME} \
              --output-path ${OUTPUT_DIR}

          # Mensaje de éxito
          echo "Documentación generada en $OUTPUT_DIR"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload only the git-page directory
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
