          swift package resolve;
          
          # Variables configurables
          SCHEME_NAME="AnnotationSwift"
          DESTINATION="generic/platform=iOS"
          OUTPUT_DIR="./deriveData"
          DOC_DIR="./docs"
          PROJECT_NAME="annotationSwift"
          REPOSITORY="experimental-annotation-swift"
          # Crear el directorio de salida si no existe
          mkdir -p $OUTPUT_DIR
          # Generar la documentación
          xcodebuild docbuild \
          -scheme $SCHEME_NAME \
          -destination $DESTINATION \
          -derivedDataPath $OUTPUT_DIR \
          -allowProvisioningUpdates
          # Mensaje de éxito

          # Buscar el archivo .doccarchive generado
          DOCS_ARCHIVE=$(find $OUTPUT_DIR -name "*.doccarchive" | head -n 1)
          echo "Archivo doccarchive creado en $DOCS_ARCHIVE"
          if [ -z "$DOCS_ARCHIVE" ]; then
            echo "No se encontró ningún archivo .doccarchive."
            exit 1
          fi
          echo "Archiving documentation..."
          
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting $DOCS_ARCHIVE \
            --output-path docs \
            --hosting-base-path $REPOSITORY;
            
          echo "** Archived documentation**"
          
          echo "<script>window.location.href += \"documentation/$PROJECT_NAME\"</script>" > docs/index.html;
