name: Deploy DocC to Github Pages
on:
  workflow_dispatch:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Force Xcode 13.3.1 
        run: sudo xcode-select -s "/Applications/Xcode_13.3.1.app"
      
      - name: Build and Transform DocC
        run: |
          # Variables configurables
          SCHEME_NAME="AnnotationSwift"
          DESTINATION="generic/platform=iOS"
          BUILD_DIR="./build"
          OUTPUT_DIR="./docs"
          PROJECT_NAME="AnnotationSwift"

          # Borrar directorio de build y output si existen
          rm -rf $BUILD_DIR
          rm -rf $OUTPUT_DIR

          # Crear el directorio de build si no existe
          mkdir -p $BUILD_DIR

          # Generar la documentación
          swift package --allow-writing-to-directory $BUILD_DIR \
          generate-documentation --target $SCHEME_NAME \
          --disable-indexing \
          --transform-for-static-hosting \
          --output-path $OUTPUT_DIR \
          --hosting-base-path "/$PROJECT_NAME"

          # Mensaje de éxito
          echo "Documentación generada en $OUTPUT_DIR"

          # Verificar si la documentación fue generada correctamente
          if [ ! -d "$OUTPUT_DIR/documentation/$PROJECT_NAME" ]; then
            echo "No se encontró la documentación generada."
            exit 1
          fi

          # Crear un archivo index.html que redirija a la ruta correcta
          cat <<EOF > $OUTPUT_DIR/index.html
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
    <title>Documentation</title>
    <script>window.location.href += 'documentation/$PROJECT_NAME'</script>
</head>
<body>
</body>
</html>
EOF

          echo "Documentación transformada y lista para hospedaje estático en $OUTPUT_DIR"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
